bokalas = 'Pienas'
puodelis = 'Alus'
print('Bokalas  = ', bokalas)
print('Puodelis  = ', puodelis)
# puodas = puodelis
# puodelis = bokalas
# bokalas = puodas
# print('Bokalas  = ', bokalas)
# print('Puodelis  = ', puodelis)
# print('Bokalas  = ', bokalas)
# print('Puodas  = ', puodas)
bokalas, puodelis = puodelis, bokalas
print('Bokalas  = ', bokalas)
print('Puodelis  = ', puodelis)
